version: "2.0"
services:
  router:
    build: ./Router/.
    ports:
      - "8000:8000"
    depends_on:
      - runsservice
      - usersservice

  usersservice:
    build: ./UsersService/.
    environment:
      USERDB_HOST: usersdb:3306
      USERDB_DATABASE: rwfusers
      USERDB_PASSWORD: elves
    depends_on:
      - usersdb

  usersdb:
    image: mysql:5.7    
    restart: always
    ports:
      - "3306:3306"    
    volumes:
      - usersdb_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: elves
      MYSQL_DATABASE: rwfusers

  runsservice:
    build: ./RunsService/.
    ports:  
      - "5000:5000"
    depends_on:
      - usersservice
      - runsdb

  runsdb:
    image: postgres:9.5.6    
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - runsdb_data:/var/lib/postgresql
    environment:
      POSTGRES_USER: elves
      POSTGRES_PASSWORD: elves
      POSTGRES_DB: rwfruns

volumes:
  runsdb_data:
  usersdb_data: